curl -X POST http://localhost:8083/connectors -H 'Content-Type: application/json' -d '{ "name": "mqtt-source-connector", "config": { "connector.class":"io.confluent.connect.mqtt.MqttSourceConnector", "mqtt.topics":"swd/iot/power_plant/weather", "kafka.topic":"kafka-source-topic", "mqtt.clientID":"kafka-source-mqtt", "mqtt.server.uri":"tcp://192.168.11.29:1883", "key.converter":"org.apache.kafka.connect.storage.StringConverter", "key.converter.schemas.enable":"false", "value.converter":"org.apache.kafka.connect.storage.StringConverter", "value.converter.schemas.enable":"false", "confluent.topic.bootstrap.servers":"kafka:9092", "confluent.topic.replication.factor":"1"}}'



curl -X POST http://localhost:8083/connectors -H 'Content-Type: application/json' -d '{ "name": "mqtt-source-connector", "config": { "connector.class":"io.confluent.connect.mqtt.MqttSourceConnector", "mqtt.topics":"swd/iot/power_plant/weather", "kafka.topic":"kafka-source-topic", "mqtt.clientID":"kafka-source-mqtt", "mqtt.server.uri":"tcp://192.168.11.29:1883", "key.converter":"org.apache.kafka.connect.storage.StringConverter", "key.converter.schemas.enable":"false", "value.converter":"org.apache.kafka.connect.storage.StringConverter", "value.converter.schemas.enable":"false", "confluent.topic.bootstrap.servers":"kafka:9092"}}'

{"name":"mqtt-source-connector","config":{"connector.class":"io.confluent.connect.mqtt.MqttSourceConnector","mqtt.topics":"swd/iot/power_plant/weather","kafka.topic":"kafka-source-topic","mqtt.clientID":"kafka-source-mqtt","mqtt.server.uri":"tcp://192.168.11.29:1883","key.converter":"org.apache.kafka.connect.storage.StringConverter","key.converter.schemas.enable":"false","value.converter":"org.apache.kafka.connect.storage.StringConverter","value.converter.schemas.enable":"false","confluent.topic.bootstrap.servers":"kafka:9092","name":"mqtt-source-connector"},"tasks":[],"type":"source"}

{"state":"FAILED","trace":"org.apache.kafka.common.errors.TimeoutException: License topic could not be created\nCaused by: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.\n","worker_id":"kafka-connect:8083","generation":18}"eyJtYWNfYWRkcmVzcyI6Ijg0Q0NBODY1NDBFOCIsInRlbXAiOjM5LCJodW1pZCI6ODB9"